baseURL: "https://macleod.in"
title: Jamie MacLeod
paginate: 99999
theme: PaperMod
enableInlineShortcodes: true
enableRobotsTXT: true

minify:
    disableXML: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: Archive
                  url: archives
                  weight: 5
                - name: Tags
                  url: tags
                  weight: 5
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    enableEmoji: true
    pygmentsUseClasses: true
    description: "Jamie MacLeod"
    authors: Jamie MacLeod
    ShowReadingTime: true
    defaultTheme: light
    ShowShareButtons: false
    displayFullLangName: false

    homeInfoParams:
        Title: "Nice to meet you! \U0001F30A"
        Content: >
            I'm **Jamie**, a Software Engineer and Manager currently working at [Primer](https://primer.io/).
    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/jamie-macleod/"
        - name: github
          url: "https://github.com/macleodmac"

taxonomies:
    category: categories
    tag: tags
    series: series

privacy:
    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
